const makePersona = (persona = {}) => ({
  units: "imperial",
  timezone: "America/Chicago",
  environmentMode: "Gym",
  equipmentAccess: "basic_gym",
  sessionLength: "45",
  preferredIntensity: "Standard",
  goalIntents: [],
  supportTierExpectation: "tier_1",
  bodyCompContext: "",
  strengthContext: "",
  enduranceContext: "",
  injuryContext: "none reported",
  loggingBehavior: "honest but imperfect",
  nutritionBehavior: "mixed adherence",
  coachInteractionBehavior: "asks for clarification when stuck",
  travelLikelihood: "low",
  likelyFailureModes: [],
  baselineMetrics: {},
  ...persona,
});

const exactAgeRange = (age = 34) => `${age}-${age}`;
const promptPersona = ({ age = 34, ...persona } = {}) => makePersona({
  ageRange: exactAgeRange(age),
  ...persona,
});

const BASE_SYNTHETIC_ATHLETE_PERSONAS = [
  makePersona({
    id: "novice_obese_beginner",
    name: "Maya",
    ageRange: "42-42",
    trainingAgeYears: 0,
    goalIntents: ["learn how to work out without getting hurt", "lose 20 pounds"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "morbidly obese beginner with low confidence, high fatigue, and no exact timeline",
    strengthContext: "deconditioned",
    enduranceContext: "walking only",
    equipmentReality: "apartment gym and treadmill",
    scheduleReality: "3 short weeknight sessions",
    injuryContext: "knees ache on stairs",
    loggingBehavior: "sporadic but honest",
    nutritionBehavior: "weekdays decent, weekends chaotic",
    coachInteractionBehavior: "needs reassurance and plain language",
    likelyFailureModes: ["over-prescription", "all-or-nothing dropout"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 288, waist: 52, startingCapacity: "10_easy_minutes" },
  }),
  makePersona({
    id: "detrained_returner",
    name: "Chris",
    ageRange: "30-39",
    trainingAgeYears: 6,
    goalIntents: ["get back into shape without blowing myself up"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "weight up after a long layoff",
    strengthContext: "used to lift, now detrained",
    enduranceContext: "low base",
    equipmentReality: "full gym",
    scheduleReality: "4 flexible sessions",
    injuryContext: "low back gets cranky when rushed",
    loggingBehavior: "good for two weeks, then drifts",
    nutritionBehavior: "generally fine but under-eats protein",
    likelyFailureModes: ["doing too much too soon", "ignoring rebuild signals"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 212, lift: { exercise: "Back Squat", weight: 185, reps: 5 } },
  }),
  makePersona({
    id: "busy_professional_recomp",
    name: "Jenna",
    ageRange: "30-39",
    trainingAgeYears: 3,
    goalIntents: ["look athletic for summer but keep my strength moving"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "recomp focus",
    strengthContext: "modest lifting base",
    enduranceContext: "conditioning tolerance is fair",
    equipmentReality: "commercial gym",
    scheduleReality: "3 reliable mornings and one optional weekend",
    loggingBehavior: "logs complete or skipped clearly",
    nutritionBehavior: "office lunches and social dinners",
    coachInteractionBehavior: "wants concise decision support",
    likelyFailureModes: ["weekend drift", "analysis overload"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 154, waist: 30, lift: { exercise: "Bench Press", weight: 115, reps: 5 } },
    programId: "program_foundation_training",
    styleId: "style_athletic_recomp",
  }),
  makePersona({
    id: "older_general_health_user",
    name: "Barbara",
    ageRange: "55-64",
    trainingAgeYears: 1,
    goalIntents: ["feel stronger and move better for daily life"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general health first",
    strengthContext: "light dumbbells only",
    enduranceContext: "walks most days",
    equipmentReality: "home dumbbells and walking",
    scheduleReality: "short morning windows",
    injuryContext: "mild hip stiffness",
    loggingBehavior: "steady if the flow stays simple",
    nutritionBehavior: "fairly consistent",
    likelyFailureModes: ["too much complexity", "fear of soreness"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 172 },
  }),
  makePersona({
    id: "physique_low_performance_interest",
    name: "Sofia",
    ageRange: "25-34",
    trainingAgeYears: 2,
    goalIntents: ["look leaner and more defined without obsessing over performance numbers"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "appearance-first",
    strengthContext: "moderate machine comfort",
    enduranceContext: "minimal conditioning interest",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions per week",
    loggingBehavior: "takes quick logs only",
    nutritionBehavior: "good weekdays, looser weekends",
    likelyFailureModes: ["scale fixation", "ignoring proxy metrics"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 141, waist: 28 },
  }),
  makePersona({
    id: "no_goal_foundation_user",
    name: "Leo",
    ageRange: "35-44",
    trainingAgeYears: 1,
    goalIntents: [],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance",
    strengthContext: "light dumbbell experience",
    enduranceContext: "walks and occasional bike",
    equipmentReality: "basic home setup",
    scheduleReality: "3 sessions when possible",
    loggingBehavior: "logs when prompted",
    nutritionBehavior: "not trying to diet hard",
    likelyFailureModes: ["no-goal indecision", "drift without clear defaults"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 188 },
  }),
  makePersona({
    id: "postpartum_returner",
    name: "Elena",
    ageRange: "30-39",
    trainingAgeYears: 4,
    goalIntents: ["rebuild consistency and core strength after having a baby"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "gentle recomposition",
    strengthContext: "former lifter rebuilding",
    enduranceContext: "walking and stroller pushes",
    equipmentReality: "home and stroller",
    scheduleReality: "fragmented naps and short windows",
    injuryContext: "pelvic floor caution and sleep disruption",
    loggingBehavior: "short honest logs",
    nutritionBehavior: "good intentions, chaotic execution",
    likelyFailureModes: ["sleep-driven fatigue", "session interruptions"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "20",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 166 },
  }),
  makePersona({
    id: "busy_new_parent",
    name: "Nate",
    ageRange: "30-39",
    trainingAgeYears: 5,
    goalIntents: ["stay strong and sane with a newborn at home"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance",
    strengthContext: "former intermediate lifter",
    enduranceContext: "no structured cardio right now",
    equipmentReality: "garage gym",
    scheduleReality: "20-minute fragments",
    loggingBehavior: "quick complete or skipped",
    nutritionBehavior: "grab-and-go",
    likelyFailureModes: ["schedule collapse", "fatigue accumulation"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "20",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 196, lift: { exercise: "Bench Press", weight: 185, reps: 5 } },
  }),
  makePersona({
    id: "bench_225_office_worker",
    name: "Marcus",
    ageRange: "25-34",
    trainingAgeYears: 4,
    goalIntents: ["bench 225"],
    supportTierExpectation: "tier_1",
    strengthContext: "intermediate upper-body lifter",
    enduranceContext: "minimal conditioning",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions per week",
    loggingBehavior: "consistent on lifts, weak on accessories",
    nutritionBehavior: "adequate calories, inconsistent protein timing",
    likelyFailureModes: ["ego jumps", "ignoring fatigue"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 183, lift: { exercise: "Bench Press", weight: 195, reps: 3 } },
    programId: "program_strength_foundation",
    styleId: "style_powerbuilding_bias",
  }),
  makePersona({
    id: "bodybuilder_prep_user",
    name: "Alicia",
    ageRange: "25-34",
    trainingAgeYears: 7,
    goalIntents: ["get stage lean while keeping muscle"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "physique-first with high adherence",
    strengthContext: "advanced machine and dumbbell work",
    enduranceContext: "conditioning tolerated when dose is clear",
    equipmentReality: "full gym",
    scheduleReality: "5 training days",
    loggingBehavior: "high detail",
    nutritionBehavior: "strong weekday compliance",
    likelyFailureModes: ["diet fatigue", "overuse from volume"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    sessionLength: "60+",
    preferredIntensity: "Aggressive",
    baselineMetrics: { bodyweight: 143, waist: 27 },
    styleId: "style_golden_era_hypertrophy",
  }),
  makePersona({
    id: "garage_gym_strength_dad",
    name: "Ryan",
    ageRange: "35-44",
    trainingAgeYears: 8,
    goalIntents: ["get stronger at home without needing a fancy gym"],
    supportTierExpectation: "tier_1",
    strengthContext: "experienced with barbells",
    enduranceContext: "walks and occasional rower",
    equipmentReality: "garage gym",
    scheduleReality: "4 early-morning sessions",
    loggingBehavior: "very consistent",
    nutritionBehavior: "solid but not meticulous",
    likelyFailureModes: ["equipment mismatch from templated gym plans"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    baselineMetrics: { bodyweight: 205, lift: { exercise: "Back Squat", weight: 315, reps: 5 } },
  }),
  makePersona({
    id: "powerlifter_cutting",
    name: "Victor",
    ageRange: "25-34",
    trainingAgeYears: 9,
    goalIntents: ["lose a class without tanking my squat and bench"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "controlled cut",
    strengthContext: "advanced powerlifting base",
    enduranceContext: "little conditioning",
    equipmentReality: "powerlifting gym",
    scheduleReality: "4 lift days",
    loggingBehavior: "precise",
    nutritionBehavior: "high compliance until social weekends",
    likelyFailureModes: ["cut too hard", "fatigue hiding under good top sets"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    sessionLength: "60+",
    baselineMetrics: { bodyweight: 219, waist: 35, lift: { exercise: "Back Squat", weight: 455, reps: 2 } },
    programId: "program_powerbuilding_builder",
  }),
  makePersona({
    id: "woman_strength_confidence",
    name: "Kira",
    ageRange: "25-34",
    trainingAgeYears: 1,
    goalIntents: ["feel confident under the bar and build real strength"],
    supportTierExpectation: "tier_1",
    strengthContext: "novice lifter who wants structure",
    enduranceContext: "minimal",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions per week",
    loggingBehavior: "does quick complete if the structure is already there",
    nutritionBehavior: "good enough, not performance-obsessed",
    likelyFailureModes: ["low confidence under heavy loads", "confusion from too much accessory noise"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 148, lift: { exercise: "Bench Press", weight: 85, reps: 5 } },
  }),
  makePersona({
    id: "home_dumbbell_beginner",
    name: "Allison",
    ageRange: "25-34",
    trainingAgeYears: 0,
    goalIntents: ["tone up and get stronger at home"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "appearance and confidence",
    strengthContext: "brand new",
    enduranceContext: "walks daily",
    equipmentReality: "adjustable dumbbells and bands",
    scheduleReality: "4 short sessions",
    loggingBehavior: "uses the simplest possible path",
    nutritionBehavior: "fairly normal",
    likelyFailureModes: ["gym-centric assumptions", "too many options"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 163 },
  }),
  makePersona({
    id: "teacher_summer_cut",
    name: "Tessa",
    ageRange: "25-34",
    trainingAgeYears: 3,
    goalIntents: ["lean out by summer break and keep some muscle"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "fat loss with muscle retention",
    strengthContext: "basic gym lifting",
    enduranceContext: "walks a lot at work",
    equipmentReality: "full gym",
    scheduleReality: "4 consistent sessions during break, less consistent during school",
    loggingBehavior: "better in bursts",
    nutritionBehavior: "meal prep works until stressful weeks",
    likelyFailureModes: ["schedule whiplash across semesters", "weekend overeating"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 158, waist: 31 },
  }),
  makePersona({
    id: "half_runner_no_date",
    name: "Evan",
    ageRange: "30-39",
    trainingAgeYears: 2,
    goalIntents: ["run a stronger half marathon this fall"],
    supportTierExpectation: "tier_1",
    enduranceContext: "3 runs per week with some history",
    equipmentReality: "roads and a basic gym",
    scheduleReality: "4 runs or 3 runs plus one lift",
    loggingBehavior: "logs mileage, rarely notes feel",
    nutritionBehavior: "under-fuels harder days",
    likelyFailureModes: ["no exact event date", "missing long-run anchor"],
    environmentMode: "Varies",
    equipmentAccess: "basic_gym",
    baselineMetrics: { bodyweight: 171, run: { distanceMiles: 7, durationMinutes: "63", paceText: "9:00" } },
    programId: "program_half_marathon_base",
    styleId: "style_marathoner_bias",
  }),
  makePersona({
    id: "marathon_event_runner",
    name: "Lena",
    ageRange: "35-44",
    trainingAgeYears: 5,
    goalIntents: ["run a marathon in November"],
    supportTierExpectation: "tier_1",
    enduranceContext: "established runner",
    equipmentReality: "road running and gym access",
    scheduleReality: "5 sessions per week",
    loggingBehavior: "strong completion history",
    nutritionBehavior: "misses recovery meals on workdays",
    likelyFailureModes: ["travel weeks", "under-fueling before long runs"],
    environmentMode: "Varies",
    equipmentAccess: "basic_gym",
    sessionLength: "60+",
    baselineMetrics: { bodyweight: 136, run: { distanceMiles: 12, durationMinutes: "108", paceText: "9:00" } },
    programId: "program_marathon_base",
    styleId: "style_marathoner_bias",
  }),
  makePersona({
    id: "beginner_5k_walker",
    name: "Rosa",
    ageRange: "45-54",
    trainingAgeYears: 0,
    goalIntents: ["run my first 5k without hating it"],
    supportTierExpectation: "tier_1",
    enduranceContext: "walking only",
    equipmentReality: "neighborhood sidewalks",
    scheduleReality: "3 short sessions",
    injuryContext: "shin splints if volume rises too fast",
    loggingBehavior: "simple and honest",
    nutritionBehavior: "normal family eating",
    likelyFailureModes: ["too much too soon", "needing run-walk honesty"],
    environmentMode: "Home",
    equipmentAccess: "none",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 184, run: { distanceMiles: 2, durationMinutes: "32", paceText: "walk-jog" } },
  }),
  makePersona({
    id: "trail_runner",
    name: "Grant",
    ageRange: "30-39",
    trainingAgeYears: 6,
    goalIntents: ["build trail running endurance for mountain days"],
    supportTierExpectation: "tier_1",
    enduranceContext: "strong trail base",
    equipmentReality: "trails, hills, and small gym",
    scheduleReality: "4 to 5 sessions",
    loggingBehavior: "logs distance but not elevation consistently",
    nutritionBehavior: "good on long days, sloppy on easy days",
    likelyFailureModes: ["terrain mismatch", "unclear climbing proxy"],
    environmentMode: "Varies",
    equipmentAccess: "basic_gym",
    baselineMetrics: { bodyweight: 162, run: { distanceMiles: 10, durationMinutes: "100", paceText: "trail effort" } },
  }),
  makePersona({
    id: "injury_prone_runner",
    name: "Harper",
    ageRange: "35-44",
    trainingAgeYears: 4,
    goalIntents: ["run consistently again without my Achilles blowing up"],
    supportTierExpectation: "tier_2",
    enduranceContext: "had a decent base before recurring injuries",
    equipmentReality: "road and gym access",
    scheduleReality: "4 sessions if healthy",
    injuryContext: "Achilles flare history",
    loggingBehavior: "logs pain when prompted",
    nutritionBehavior: "fine overall",
    likelyFailureModes: ["impact spikes", "overconfident return-to-run jumps"],
    environmentMode: "Varies",
    equipmentAccess: "basic_gym",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 149, run: { distanceMiles: 4, durationMinutes: "40", paceText: "easy" } },
  }),
  makePersona({
    id: "travel_heavy_consultant_runner",
    name: "Priya",
    ageRange: "30-39",
    trainingAgeYears: 4,
    goalIntents: ["stay lean and keep training while traveling"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance recomp",
    strengthContext: "hotel-gym capable",
    enduranceContext: "walks a lot while traveling",
    equipmentReality: "hotel gyms and bodyweight",
    scheduleReality: "chaotic weekdays",
    loggingBehavior: "quick logs only",
    nutritionBehavior: "airport and restaurant heavy",
    coachInteractionBehavior: "asks for substitutions",
    travelLikelihood: "high",
    likelyFailureModes: ["equipment mismatch", "schedule collapse", "grocery friction"],
    environmentMode: "Travel",
    equipmentAccess: "basic_gym",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 138 },
    programId: "program_hotel_gym_travel_build",
    styleId: "style_hotel_gym_travel_mode",
  }),
  makePersona({
    id: "hotel_gym_sales_rep",
    name: "Damon",
    ageRange: "35-44",
    trainingAgeYears: 3,
    goalIntents: ["keep my conditioning and strength from falling apart on the road"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance",
    strengthContext: "moderate",
    enduranceContext: "decent base",
    equipmentReality: "hotel gyms and parking lots",
    scheduleReality: "unpredictable",
    loggingBehavior: "logs in bursts",
    nutritionBehavior: "convenience-store heavy",
    travelLikelihood: "high",
    likelyFailureModes: ["travel fatigue", "equipment downgrade", "meal-plan disruption"],
    environmentMode: "Travel",
    equipmentAccess: "basic_gym",
    sessionLength: "20",
    baselineMetrics: { bodyweight: 192 },
    styleId: "style_hotel_gym_travel_mode",
  }),
  makePersona({
    id: "marathoner_hal_program_user",
    name: "Cory",
    ageRange: "35-44",
    trainingAgeYears: 4,
    goalIntents: ["run a half marathon on a Hal-style structure"],
    supportTierExpectation: "tier_1",
    enduranceContext: "recreational runner",
    equipmentReality: "roads and gym access",
    scheduleReality: "4 runs per week",
    loggingBehavior: "completes most sessions",
    nutritionBehavior: "adequate, low detail",
    likelyFailureModes: ["program fidelity confusion", "template vs adaptation ambiguity"],
    environmentMode: "Varies",
    equipmentAccess: "basic_gym",
    baselineMetrics: { bodyweight: 175, run: { distanceMiles: 8, durationMinutes: "72", paceText: "9:00" } },
    programId: "program_hal_higdon_inspired_half",
    styleId: "style_marathoner_bias",
  }),
  makePersona({
    id: "recreational_swimmer",
    name: "Tori",
    ageRange: "25-34",
    trainingAgeYears: 2,
    goalIntents: ["swim a faster mile"],
    supportTierExpectation: "tier_2",
    enduranceContext: "pool swimmer with weak structure",
    equipmentReality: "pool plus occasional dumbbells",
    scheduleReality: "3 swim slots and 1 optional strength slot",
    loggingBehavior: "logs sessions, forgets splits",
    nutritionBehavior: "fine daily, weak around morning swims",
    likelyFailureModes: ["missing pace anchor", "pool access changes"],
    environmentMode: "Varies",
    equipmentAccess: "mixed",
    baselineMetrics: { bodyweight: 149, swim: { distance: 1000, duration: "22:30", note: "steady aerobic" } },
  }),
  makePersona({
    id: "masters_swimmer_miler",
    name: "Noah",
    ageRange: "45-54",
    trainingAgeYears: 10,
    goalIntents: ["swim a faster mile at masters nationals"],
    supportTierExpectation: "tier_2",
    enduranceContext: "experienced swimmer",
    equipmentReality: "pool with dryland",
    scheduleReality: "5 sessions with some doubles",
    injuryContext: "shoulder irritation if pull volume spikes",
    loggingBehavior: "detail oriented",
    nutritionBehavior: "good overall",
    likelyFailureModes: ["shoulder flare", "too much threshold density"],
    environmentMode: "Varies",
    equipmentAccess: "mixed",
    sessionLength: "60+",
    baselineMetrics: { bodyweight: 176, swim: { distance: 1650, duration: "25:20", note: "current mile" } },
  }),
  makePersona({
    id: "open_water_swim_novice",
    name: "Naomi",
    ageRange: "30-39",
    trainingAgeYears: 1,
    goalIntents: ["finish an open-water swim comfortably"],
    supportTierExpectation: "tier_2",
    enduranceContext: "can swim laps but gets anxious outdoors",
    equipmentReality: "pool access, no coach on deck",
    scheduleReality: "3 sessions per week",
    loggingBehavior: "logs distance, not always effort",
    nutritionBehavior: "fine",
    likelyFailureModes: ["skill confidence gap", "missing sighting/open-water specificity"],
    environmentMode: "Varies",
    equipmentAccess: "none",
    baselineMetrics: { swim: { distance: 800, duration: "20:00", note: "pool only" } },
  }),
  makePersona({
    id: "vertical_jump_basketball",
    name: "Darius",
    ageRange: "18-24",
    trainingAgeYears: 4,
    goalIntents: ["jump higher for basketball"],
    supportTierExpectation: "tier_2",
    strengthContext: "solid lower-body strength",
    enduranceContext: "court conditioning only",
    equipmentReality: "full gym and court",
    scheduleReality: "4 sessions plus pickup",
    injuryContext: "patellar tendon soreness after too much jump volume",
    loggingBehavior: "tracks jumps but not all lifts",
    nutritionBehavior: "under-eats on class-heavy days",
    likelyFailureModes: ["too much plyo density", "missing tendon tolerance history"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 191, jump: { value: 28, unit: "in" }, lift: { exercise: "Trap Bar Deadlift", weight: 365, reps: 3 } },
  }),
  makePersona({
    id: "volleyball_jump_user",
    name: "Cami",
    ageRange: "18-24",
    trainingAgeYears: 5,
    goalIntents: ["improve my vertical and stay springy for volleyball"],
    supportTierExpectation: "tier_2",
    strengthContext: "moderate lower-body strength",
    enduranceContext: "sport conditioning only",
    equipmentReality: "gym and court",
    scheduleReality: "3 lifts plus team practice",
    injuryContext: "ankles get cranky when landing volume spikes",
    loggingBehavior: "good on jumps, mixed on lifting details",
    nutritionBehavior: "often under-eats around practice",
    likelyFailureModes: ["contact-count overload", "team-practice fatigue not reflected"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 159, jump: { value: 24, unit: "in" } },
  }),
  makePersona({
    id: "basketball_guard_speed",
    name: "Miles",
    ageRange: "18-24",
    trainingAgeYears: 4,
    goalIntents: ["get more explosive and keep my lower body fresh for hoops"],
    supportTierExpectation: "tier_2",
    strengthContext: "good strength base",
    enduranceContext: "sport-specific",
    equipmentReality: "court and full gym",
    scheduleReality: "practice plus 3 extra sessions",
    injuryContext: "shin and knee soreness if load stacks badly",
    loggingBehavior: "quick session logs",
    nutritionBehavior: "college dining hall inconsistency",
    likelyFailureModes: ["too much lower-body fatigue", "unclear tradeoff with court work"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 177, jump: { value: 30, unit: "in" } },
  }),
  makePersona({
    id: "hybrid_athlete_split",
    name: "Sam",
    ageRange: "25-34",
    trainingAgeYears: 5,
    goalIntents: ["be a hybrid athlete and keep my lifts respectable"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "leans performance over aesthetics",
    strengthContext: "intermediate barbell base",
    enduranceContext: "moderate run base",
    equipmentReality: "full gym and road access",
    scheduleReality: "5 sessions max",
    loggingBehavior: "honest but misses easy sessions",
    nutritionBehavior: "good protein, variable carbs",
    likelyFailureModes: ["competing priorities", "poor tradeoff clarity"],
    environmentMode: "Varies",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 179, lift: { exercise: "Back Squat", weight: 255, reps: 5 }, run: { distanceMiles: 5, durationMinutes: "41", paceText: "8:12" } },
  }),
  makePersona({
    id: "triathlon_sprinter",
    name: "Parker",
    ageRange: "30-39",
    trainingAgeYears: 3,
    goalIntents: ["train for a sprint triathlon"],
    supportTierExpectation: "tier_3",
    enduranceContext: "some cycling and running, weak swim",
    equipmentReality: "pool, bike trainer, roads",
    scheduleReality: "5 sessions possible",
    loggingBehavior: "tracks bike and run better than swim",
    nutritionBehavior: "decent",
    likelyFailureModes: ["multi-sport mapping gaps", "adapter confidence limits"],
    environmentMode: "Varies",
    equipmentAccess: "mixed",
    sessionLength: "60+",
    baselineMetrics: { run: { distanceMiles: 4, durationMinutes: "34", paceText: "8:30" }, swim: { distance: 400, duration: "9:00", note: "limited swim base" } },
  }),
  makePersona({
    id: "dancer_power_endurance",
    name: "Ari",
    ageRange: "18-24",
    trainingAgeYears: 6,
    goalIntents: ["build dance stamina and explosiveness without getting bulky"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "appearance-sensitive",
    strengthContext: "bodyweight and light resistance",
    enduranceContext: "high rehearsal volume",
    equipmentReality: "studio and bands",
    scheduleReality: "rehearsal-heavy evenings",
    injuryContext: "Achilles and foot soreness risk",
    loggingBehavior: "inconsistent outside of rehearsals",
    nutritionBehavior: "under-eats on busy days",
    likelyFailureModes: ["niche sport mapping", "durability under dance volume"],
    environmentMode: "Home",
    equipmentAccess: "none",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 126 },
  }),
  makePersona({
    id: "office_worker_low_back",
    name: "Ben",
    ageRange: "35-44",
    trainingAgeYears: 2,
    goalIntents: ["get strong again without making my low back worse"],
    supportTierExpectation: "tier_2",
    strengthContext: "used to lift, now careful",
    enduranceContext: "light walking only",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions after work",
    injuryContext: "recurring low-back pain",
    loggingBehavior: "good when pain is low",
    nutritionBehavior: "average",
    likelyFailureModes: ["hinge fear", "pain context not carried forward"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 201 },
  }),
  makePersona({
    id: "senior_rehab_walk",
    name: "Walter",
    ageRange: "65-74",
    trainingAgeYears: 0,
    goalIntents: ["walk farther and rebuild confidence after rehab"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "general health",
    strengthContext: "very low current strength",
    enduranceContext: "walking rebuild",
    equipmentReality: "home and neighborhood",
    scheduleReality: "daily short windows",
    injuryContext: "post-rehab caution",
    loggingBehavior: "very simple",
    nutritionBehavior: "stable home meals",
    likelyFailureModes: ["too much intensity", "poor gait/tolerance honesty"],
    environmentMode: "Home",
    equipmentAccess: "none",
    sessionLength: "20",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 178 },
  }),
  makePersona({
    id: "crossfit_burnout_returner",
    name: "Erik",
    ageRange: "30-39",
    trainingAgeYears: 7,
    goalIntents: ["rebuild consistency without redlining like I used to"],
    supportTierExpectation: "tier_1",
    strengthContext: "strong base",
    enduranceContext: "good work capacity",
    equipmentReality: "well-equipped gym",
    scheduleReality: "4 sessions",
    injuryContext: "nagging shoulder and fatigue history",
    loggingBehavior: "good",
    nutritionBehavior: "undereats on busy days",
    likelyFailureModes: ["excess aggression", "volume creep"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 198, lift: { exercise: "Front Squat", weight: 245, reps: 3 } },
  }),
  makePersona({
    id: "injury_prone_athlete",
    name: "Mikayla",
    ageRange: "25-34",
    trainingAgeYears: 5,
    goalIntents: ["stay athletic without constantly getting hurt"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "maintenance",
    strengthContext: "good base but inconsistent continuity",
    enduranceContext: "mixed field sport history",
    equipmentReality: "gym plus field",
    scheduleReality: "4 sessions",
    injuryContext: "hamstring and ankle history",
    loggingBehavior: "honest if the app asks simply",
    nutritionBehavior: "good enough",
    likelyFailureModes: ["durability context not visible", "too much novelty"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 150, jump: { value: 22, unit: "in" } },
  }),
  makePersona({
    id: "firefighter_candidate",
    name: "Zane",
    ageRange: "18-24",
    trainingAgeYears: 2,
    goalIntents: ["prepare for firefighter academy fitness demands"],
    supportTierExpectation: "tier_3",
    strengthContext: "decent base",
    enduranceContext: "some conditioning",
    equipmentReality: "full gym",
    scheduleReality: "5 sessions possible",
    loggingBehavior: "committed",
    nutritionBehavior: "basic high-protein approach",
    likelyFailureModes: ["tactical specificity gaps", "carry and drag demand not explicit"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 188 },
  }),
  makePersona({
    id: "police_shift_worker",
    name: "Devin",
    ageRange: "30-39",
    trainingAgeYears: 4,
    goalIntents: ["stay fit and durable on rotating police shifts"],
    supportTierExpectation: "tier_3",
    strengthContext: "moderate",
    enduranceContext: "okay conditioning",
    equipmentReality: "station gym and home",
    scheduleReality: "rotating shifts with sleep disruption",
    injuryContext: "knees and low back can flare",
    loggingBehavior: "quick logs only",
    nutritionBehavior: "overnight shift eating is messy",
    likelyFailureModes: ["shift-specific fatigue", "nutrition timing drift"],
    environmentMode: "Varies",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 207 },
  }),
  makePersona({
    id: "shift_nurse_recomp",
    name: "Kayla",
    ageRange: "25-34",
    trainingAgeYears: 3,
    goalIntents: ["lose fat and keep energy steady on hospital shifts"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "recomp",
    strengthContext: "basic gym base",
    enduranceContext: "workday steps are high",
    equipmentReality: "commercial gym",
    scheduleReality: "three long shifts and two off-day training windows",
    loggingBehavior: "quick and honest",
    nutritionBehavior: "night-shift snacking is the main issue",
    likelyFailureModes: ["late-day drift", "under-recovery between shifts"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 169, waist: 32 },
  }),
  makePersona({
    id: "executive_airport_eater",
    name: "Monica",
    ageRange: "40-49",
    trainingAgeYears: 4,
    goalIntents: ["stay lean and functional with constant flights"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance",
    strengthContext: "moderate",
    enduranceContext: "walk-heavy travel days",
    equipmentReality: "hotel gyms, airport terminals, bodyweight",
    scheduleReality: "very compressed",
    loggingBehavior: "only fast logging will happen",
    nutritionBehavior: "airport and catered-meeting heavy",
    travelLikelihood: "high",
    likelyFailureModes: ["travel friction", "meal-plan realism gaps"],
    environmentMode: "Travel",
    equipmentAccess: "basic_gym",
    sessionLength: "20",
    baselineMetrics: { bodyweight: 134 },
    styleId: "style_hotel_gym_travel_mode",
  }),
  makePersona({
    id: "military_prep_candidate",
    name: "Aaron",
    ageRange: "18-24",
    trainingAgeYears: 2,
    goalIntents: ["prepare for military fitness testing and selection"],
    supportTierExpectation: "tier_3",
    strengthContext: "bodyweight and some barbell work",
    enduranceContext: "running matters",
    equipmentReality: "gym and track",
    scheduleReality: "5 sessions",
    loggingBehavior: "committed",
    nutritionBehavior: "basic but not precise",
    likelyFailureModes: ["test specificity gaps", "load-carriage not explicit"],
    environmentMode: "Varies",
    equipmentAccess: "full_gym",
    baselineMetrics: { run: { distanceMiles: 2, durationMinutes: "15:30", paceText: "test pace" }, bodyweight: 176 },
  }),
  makePersona({
    id: "college_soccer_returner",
    name: "Imani",
    ageRange: "18-24",
    trainingAgeYears: 7,
    goalIntents: ["get fit enough to play competitive soccer again"],
    supportTierExpectation: "tier_2",
    strengthContext: "moderate",
    enduranceContext: "former match fitness, now detrained",
    equipmentReality: "field and gym",
    scheduleReality: "4 to 5 sessions",
    injuryContext: "hamstring history",
    loggingBehavior: "pretty good",
    nutritionBehavior: "reasonable",
    likelyFailureModes: ["field-sport specificity", "sprint exposure tolerance"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 147, run: { distanceMiles: 3, durationMinutes: "26", paceText: "8:40" } },
  }),
  makePersona({
    id: "recreational_tennis_league",
    name: "Dylan",
    ageRange: "35-44",
    trainingAgeYears: 3,
    goalIntents: ["feel quicker and less gassed for league tennis"],
    supportTierExpectation: "tier_2",
    strengthContext: "modest gym work",
    enduranceContext: "court conditioning only",
    equipmentReality: "tennis courts and gym",
    scheduleReality: "2 matches plus 2 training sessions",
    injuryContext: "elbow and calf management matter",
    loggingBehavior: "logs when prompted",
    nutritionBehavior: "fine",
    likelyFailureModes: ["court-specific agility mapping", "match load not captured"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 182 },
  }),
  makePersona({
    id: "pickleball_retiree",
    name: "Elaine",
    ageRange: "60-69",
    trainingAgeYears: 1,
    goalIntents: ["keep playing pickleball without feeling beat up"],
    supportTierExpectation: "tier_2",
    strengthContext: "light strength only",
    enduranceContext: "court sessions are the main conditioning",
    equipmentReality: "court plus light home setup",
    scheduleReality: "3 to 4 sessions a week",
    injuryContext: "shoulder and Achilles caution",
    loggingBehavior: "simple",
    nutritionBehavior: "steady",
    likelyFailureModes: ["durability support needs", "sport specificity honesty"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 152 },
  }),
  makePersona({
    id: "climber_body_comp",
    name: "Hugo",
    ageRange: "25-34",
    trainingAgeYears: 5,
    goalIntents: ["get leaner and keep my climbing performance up"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "lean out without losing pulling strength",
    strengthContext: "climbing specific",
    enduranceContext: "indoor climbing sessions",
    equipmentReality: "climbing gym and dumbbells",
    scheduleReality: "4 sessions plus 2 climbs",
    loggingBehavior: "logs training better than climbing",
    nutritionBehavior: "under-fuels long climbing days",
    likelyFailureModes: ["sport-specific metric gaps", "finger and shoulder durability not explicit"],
    environmentMode: "Varies",
    equipmentAccess: "dumbbells",
    baselineMetrics: { bodyweight: 160 },
  }),
  makePersona({
    id: "peloton_plus_strength_user",
    name: "Heather",
    ageRange: "35-44",
    trainingAgeYears: 2,
    goalIntents: ["use my bike and dumbbells to get fitter without overthinking it"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "mild recomposition",
    strengthContext: "dumbbell only",
    enduranceContext: "bike intervals",
    equipmentReality: "Peloton and dumbbells",
    scheduleReality: "4 short sessions",
    loggingBehavior: "fast logs",
    nutritionBehavior: "reasonable",
    likelyFailureModes: ["equipment mismatch", "bike not treated as real conditioning"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 157 },
  }),
  makePersona({
    id: "minimalist_foundation_user",
    name: "Paul",
    ageRange: "40-49",
    trainingAgeYears: 0,
    goalIntents: ["just give me a sensible foundation plan I can follow"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general health",
    strengthContext: "none",
    enduranceContext: "walks sometimes",
    equipmentReality: "bodyweight and bands",
    scheduleReality: "3 short slots",
    loggingBehavior: "only quick complete",
    nutritionBehavior: "normal",
    likelyFailureModes: ["too much explanation", "too much input burden"],
    environmentMode: "Home",
    equipmentAccess: "none",
    sessionLength: "20",
    baselineMetrics: {},
  }),
  makePersona({
    id: "ocr_weekend_warrior",
    name: "Nico",
    ageRange: "30-39",
    trainingAgeYears: 4,
    goalIntents: ["improve obstacle course race fitness"],
    supportTierExpectation: "tier_3",
    strengthContext: "decent",
    enduranceContext: "moderate run base",
    equipmentReality: "gym and trail access",
    scheduleReality: "4 sessions",
    loggingBehavior: "pretty good",
    nutritionBehavior: "mixed",
    likelyFailureModes: ["obstacle-specific skill gap", "grip and carry work not explicit"],
    environmentMode: "Varies",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 186, run: { distanceMiles: 5, durationMinutes: "43", paceText: "8:36" } },
  }),
  makePersona({
    id: "fighter_lean_aesthetic",
    name: "Isaac",
    ageRange: "25-34",
    trainingAgeYears: 5,
    goalIntents: ["get lean like a fighter without actually training for fights"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "physique plus conditioning",
    strengthContext: "moderate",
    enduranceContext: "likes circuits",
    equipmentReality: "full gym",
    scheduleReality: "5 sessions",
    loggingBehavior: "consistent",
    nutritionBehavior: "good when the structure is simple",
    likelyFailureModes: ["style vs backbone confusion", "conditioning excess"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 174, waist: 33 },
    styleId: "style_fight_camp_lean",
  }),
  makePersona({
    id: "mma_lean_user",
    name: "Rafi",
    ageRange: "25-34",
    trainingAgeYears: 6,
    goalIntents: ["stay fight-camp lean and explosive for sparring"],
    supportTierExpectation: "tier_2",
    strengthContext: "good power base",
    enduranceContext: "combat conditioning",
    equipmentReality: "mma gym plus weights",
    scheduleReality: "skill work plus 3 training sessions",
    loggingBehavior: "skill work logs are sparse",
    nutritionBehavior: "weight-cut instincts are too aggressive",
    likelyFailureModes: ["combat-sport specificity", "under-fueling"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 168 },
    styleId: "style_fight_camp_lean",
  }),
  makePersona({
    id: "college_rower_offseason",
    name: "Brooke",
    ageRange: "18-24",
    trainingAgeYears: 6,
    goalIntents: ["stay strong and conditioned in rowing offseason"],
    supportTierExpectation: "tier_3",
    strengthContext: "good lower-body and pulling strength",
    enduranceContext: "rowing-specific engine",
    equipmentReality: "erg and full gym",
    scheduleReality: "5 sessions",
    loggingBehavior: "erg data rich, everything else lighter",
    nutritionBehavior: "good on training days",
    likelyFailureModes: ["rowing-specific metrics not modeled", "erg transfer assumptions"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 165 },
  }),
  makePersona({
    id: "older_return_to_health",
    name: "Dennis",
    ageRange: "50-59",
    trainingAgeYears: 0,
    goalIntents: ["feel better, lose some weight, and stop starting over"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "weight loss",
    strengthContext: "very low",
    enduranceContext: "walking only",
    equipmentReality: "home treadmill and bands",
    scheduleReality: "3 short sessions",
    loggingBehavior: "better when the app stays calm",
    nutritionBehavior: "family dinners are the hardest part",
    likelyFailureModes: ["motivation dips", "overwhelming setup"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 232, waist: 44 },
  }),
  makePersona({
    id: "beach_vacation_appearance",
    name: "Lily",
    ageRange: "25-34",
    trainingAgeYears: 2,
    goalIntents: ["look athletic for a beach trip in July"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "appearance deadline",
    strengthContext: "light gym experience",
    enduranceContext: "some classes and walks",
    equipmentReality: "commercial gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good until travel weekends",
    nutritionBehavior: "weekday structure, weekend drift",
    likelyFailureModes: ["deadline anxiety", "waist and bodyweight proxies missing"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 147, waist: 29 },
    styleId: "style_athletic_recomp",
  }),
  makePersona({
    id: "summer_athletic_wedding",
    name: "Colin",
    ageRange: "30-39",
    trainingAgeYears: 3,
    goalIntents: ["look lean and athletic for my wedding but keep my bench moving"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "recomp",
    strengthContext: "bench-focused",
    enduranceContext: "supportive only",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good",
    nutritionBehavior: "very good on weekdays",
    likelyFailureModes: ["split-focus tradeoff honesty"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 185, waist: 34, lift: { exercise: "Bench Press", weight: 205, reps: 2 } },
  }),
  makePersona({
    id: "desk_worker_foundation",
    name: "Megan",
    ageRange: "30-39",
    trainingAgeYears: 0,
    goalIntents: ["move more and feel less stiff from desk work"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general health",
    strengthContext: "none",
    enduranceContext: "some walking",
    equipmentReality: "home and office gym",
    scheduleReality: "3 sessions",
    injuryContext: "neck and hip stiffness",
    loggingBehavior: "simple",
    nutritionBehavior: "average",
    likelyFailureModes: ["too much friction to start", "needs mobility and consistency more than complexity"],
    environmentMode: "Home",
    equipmentAccess: "none",
    sessionLength: "20",
    baselineMetrics: { bodyweight: 174 },
  }),
  makePersona({
    id: "young_male_mass_gain",
    name: "Trey",
    ageRange: "18-24",
    trainingAgeYears: 2,
    goalIntents: ["gain muscle without getting sloppy"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "lean gain",
    strengthContext: "novice-intermediate",
    enduranceContext: "minimal",
    equipmentReality: "full gym",
    scheduleReality: "5 sessions",
    loggingBehavior: "good in gym, weak elsewhere",
    nutritionBehavior: "undereats when busy",
    likelyFailureModes: ["protein and calorie misses", "junk-bulk impulse"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    sessionLength: "60+",
    preferredIntensity: "Aggressive",
    baselineMetrics: { bodyweight: 158, lift: { exercise: "Bench Press", weight: 145, reps: 5 } },
  }),
  makePersona({
    id: "masters_lifter_over50",
    name: "Glen",
    ageRange: "50-59",
    trainingAgeYears: 12,
    goalIntents: ["keep getting stronger without digging a recovery hole"],
    supportTierExpectation: "tier_1",
    strengthContext: "advanced lifting age, slower recovery",
    enduranceContext: "walks and bikes",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions",
    injuryContext: "elbows and hips need warm-up care",
    loggingBehavior: "excellent",
    nutritionBehavior: "solid",
    likelyFailureModes: ["aggressive jumps outpacing recovery", "volume tolerance not age-aware enough"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    preferredIntensity: "Standard",
    baselineMetrics: { bodyweight: 196, lift: { exercise: "Deadlift", weight: 405, reps: 3 } },
  }),
  makePersona({
    id: "celebrity_look_request",
    name: "Jordan",
    ageRange: "25-34",
    trainingAgeYears: 2,
    goalIntents: ["look like a movie action hero by summer"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "appearance-first with unrealistic comparison bias",
    strengthContext: "basic lifting experience",
    enduranceContext: "mixed",
    equipmentReality: "commercial gym",
    scheduleReality: "4 to 5 sessions",
    loggingBehavior: "inconsistent when expectations feel too high",
    nutritionBehavior: "wants a perfect plan, does not follow it perfectly",
    likelyFailureModes: ["celebrity protocol chasing", "unrealistic timeline"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 177, waist: 34 },
  }),
  makePersona({
    id: "hyrox_style_user",
    name: "Seth",
    ageRange: "30-39",
    trainingAgeYears: 4,
    goalIntents: ["get fitter for Hyrox-style events"],
    supportTierExpectation: "tier_3",
    strengthContext: "moderate",
    enduranceContext: "good conditioning",
    equipmentReality: "full gym and sled access sometimes",
    scheduleReality: "5 sessions",
    loggingBehavior: "good",
    nutritionBehavior: "pretty solid",
    likelyFailureModes: ["event-specific station mapping", "niche race support honesty"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    baselineMetrics: { bodyweight: 186 },
  }),
  makePersona({
    id: "busy_professional_3day_program_user",
    name: "Avery",
    ageRange: "35-44",
    trainingAgeYears: 3,
    goalIntents: ["get stronger and leaner on three days a week"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "recomp",
    strengthContext: "intermediate",
    enduranceContext: "light conditioning",
    equipmentReality: "full gym",
    scheduleReality: "strictly 3 sessions",
    loggingBehavior: "good if the plan respects time",
    nutritionBehavior: "solid weekdays",
    likelyFailureModes: ["program fit vs schedule reality"],
    environmentMode: "Gym",
    equipmentAccess: "full_gym",
    sessionLength: "45",
    baselineMetrics: { bodyweight: 193, lift: { exercise: "Back Squat", weight: 245, reps: 5 } },
    programId: "program_busy_professional_3day_performance",
  }),
  makePersona({
    id: "minimal_equipment_conditioning_user",
    name: "Renee",
    ageRange: "30-39",
    trainingAgeYears: 1,
    goalIntents: ["stay conditioned with minimal equipment"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance",
    strengthContext: "light dumbbells only",
    enduranceContext: "conditioning-focused",
    equipmentReality: "bands, dumbbells, bodyweight",
    scheduleReality: "4 short sessions",
    loggingBehavior: "quick logs",
    nutritionBehavior: "steady",
    likelyFailureModes: ["home-equipment assumptions drift"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 151 },
    programId: "program_minimal_equipment_conditioning",
  }),
];

const ADDITIONAL_ADVERSARIAL_PERSONAS = [
  promptPersona({
    id: "former_athlete_look_athletic_again",
    name: "Noah",
    age: 29,
    trainingAgeYears: 6,
    goalIntents: ["I want to look athletic again"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "vague aesthetic goal with high expectations",
    strengthContext: "former field athlete, now detrained",
    enduranceContext: "occasional cardio only",
    equipmentReality: "commercial gym",
    scheduleReality: "4 sessions with motivation swings",
    loggingBehavior: "strong first two weeks, then patchy",
    nutritionBehavior: "decent weekdays, social weekends",
    coachInteractionBehavior: "asks for clarification when expectations drift",
    likelyFailureModes: ["needs clear proxies", "high expectation gap"],
    baselineMetrics: { bodyweight: 182, waist: 34, lift: { exercise: "Bench Press", weight: 165, reps: 5 } },
  }),
  promptPersona({
    id: "busy_lawyer_fat_loss",
    name: "Megan",
    age: 39,
    trainingAgeYears: 2,
    goalIntents: ["lose fat without blowing up my schedule"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "fat loss with repeated missed sessions",
    strengthContext: "some prior lifting",
    enduranceContext: "sporadic incline walking",
    equipmentReality: "commercial gym near the office",
    scheduleReality: "3 sessions with frequent late meetings",
    loggingBehavior: "honest but incomplete when busy",
    nutritionBehavior: "restaurant lunches and missed dinners",
    coachInteractionBehavior: "rarely chats with coach",
    likelyFailureModes: ["missed sessions", "schedule compression"],
    baselineMetrics: { bodyweight: 208, waist: 39 },
  }),
  promptPersona({
    id: "college_student_abs_strength",
    name: "Evan",
    age: 20,
    trainingAgeYears: 1,
    goalIntents: ["get abs", "get stronger"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "appearance plus novice strength",
    strengthContext: "beginner barbell exposure",
    enduranceContext: "walk-heavy campus routine",
    equipmentReality: "student rec center",
    scheduleReality: "2 to 5 sessions depending on classes",
    loggingBehavior: "bursty and inconsistent",
    nutritionBehavior: "cafeteria weekdays, chaotic weekends",
    coachInteractionBehavior: "overuses coach when the week falls apart",
    likelyFailureModes: ["schedule swings", "motivation whiplash"],
    baselineMetrics: { bodyweight: 171, waist: 33, lift: { exercise: "Bench Press", weight: 115, reps: 5 } },
  }),
  promptPersona({
    id: "beginner_male_six_pack_summer",
    name: "Caleb",
    age: 27,
    trainingAgeYears: 0,
    goalIntents: ["get a six pack by summer"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "beginner appearance goal with weak timeline realism",
    strengthContext: "new to training",
    enduranceContext: "some casual sports",
    equipmentReality: "basic gym",
    scheduleReality: "3 sessions",
    loggingBehavior: "good when motivated",
    nutritionBehavior: "low nutrition literacy",
    coachInteractionBehavior: "asks for reassurance often",
    likelyFailureModes: ["timeline mismatch", "scale fixation"],
    baselineMetrics: { bodyweight: 196, waist: 38, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "beginner_female_tone_up_home",
    name: "Lila",
    age: 26,
    trainingAgeYears: 0,
    goalIntents: ["tone up at home"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "appearance-first and gym-culture avoidant",
    strengthContext: "beginner home training",
    enduranceContext: "walks often",
    equipmentReality: "apartment dumbbells and bands",
    scheduleReality: "3 short home sessions",
    loggingBehavior: "simple check-ins only",
    nutritionBehavior: "steady but not meticulous",
    coachInteractionBehavior: "never chats unless stuck",
    likelyFailureModes: ["copy tone mismatch", "home-equipment mismatch"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 142, waist: 29 },
  }),
  promptPersona({
    id: "older_adult_capable_mobility",
    name: "Diane",
    age: 61,
    trainingAgeYears: 1,
    goalIntents: ["stay capable and keep my mobility"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general health and capability",
    strengthContext: "light dumbbells and machines",
    enduranceContext: "walks most days",
    equipmentReality: "light gym and home bands",
    scheduleReality: "4 short morning sessions",
    injuryContext: "mild hip and shoulder stiffness",
    loggingBehavior: "steady if the product stays simple",
    nutritionBehavior: "consistent",
    coachInteractionBehavior: "prefers short answers and no drama",
    likelyFailureModes: ["too much aggressive language", "mobility copy mismatch"],
    sessionLength: "30",
    baselineMetrics: { bodyweight: 168, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "retired_swimmer_conditioning",
    name: "Alan",
    age: 68,
    trainingAgeYears: 10,
    goalIntents: ["general conditioning", "shoulder-friendly strength work"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "health and conditioning",
    strengthContext: "shoulder-aware dumbbell work",
    enduranceContext: "retired swimmer comfortable in the pool",
    equipmentReality: "pool and light dumbbells",
    scheduleReality: "3 pool or strength sessions",
    injuryContext: "shoulders dislike heavy pressing",
    loggingBehavior: "simple and steady",
    nutritionBehavior: "steady",
    likelyFailureModes: ["swim-strength bridge can feel awkward", "shoulder sensitivity"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    baselineMetrics: {
      bodyweight: 176,
      swim: { distance: 800, distanceUnit: "yd", duration: "19:00", raw: "800 yd in 19:00" },
      swimAccessReality: "pool",
    },
  }),
  promptPersona({
    id: "hotel_travel_strength_fat_loss",
    name: "Priya",
    age: 41,
    trainingAgeYears: 4,
    goalIntents: ["maintain strength", "lose 10 pounds"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "fat loss while traveling heavily",
    strengthContext: "competent hotel-gym lifter",
    enduranceContext: "walk-heavy travel days",
    equipmentReality: "hotel gyms only",
    scheduleReality: "3 compressed travel sessions",
    loggingBehavior: "honest but rushed",
    nutritionBehavior: "airport food and client dinners",
    coachInteractionBehavior: "wants concise decision support",
    travelLikelihood: "high",
    likelyFailureModes: ["baseline timing on mixed goals", "travel compression"],
    environmentMode: "Travel",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 204, waist: 39, lift: { exercise: "Bench Press", weight: 165, reps: 5 } },
  }),
  promptPersona({
    id: "pickup_basketball_dad",
    name: "Omar",
    age: 40,
    trainingAgeYears: 3,
    goalIntents: ["stop blowing out calves and knees playing pickup basketball"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "general fitness",
    strengthContext: "basic lifting with low consistency",
    enduranceContext: "pickup basketball once a week",
    equipmentReality: "community gym",
    scheduleReality: "2 gym sessions plus weekend basketball",
    injuryContext: "calf strains and cranky knees",
    loggingBehavior: "logs soreness more than workouts",
    nutritionBehavior: "average",
    likelyFailureModes: ["pain flare handling", "lower-body recovery mismatch"],
    baselineMetrics: { bodyweight: 211, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "jiu_jitsu_cut_performance",
    name: "Marco",
    age: 35,
    trainingAgeYears: 5,
    goalIntents: ["cut weight slowly", "keep performance for jiu-jitsu"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "slow cut without performance collapse",
    strengthContext: "basic strength maintenance",
    enduranceContext: "combat conditioning",
    equipmentReality: "grappling gym and basic weights",
    scheduleReality: "4 training sessions",
    loggingBehavior: "good with training, weak with food",
    nutritionBehavior: "weight-cut instincts can get extreme",
    coachInteractionBehavior: "asks for plan changes before tournaments",
    likelyFailureModes: ["over-cutting", "performance tradeoff confusion"],
    baselineMetrics: { bodyweight: 196, waist: 37 },
  }),
  promptPersona({
    id: "boxing_fighter_shape",
    name: "Andre",
    age: 29,
    trainingAgeYears: 3,
    goalIntents: ["get in fighter shape"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "vague appearance plus conditioning language",
    strengthContext: "bodyweight and bag work",
    enduranceContext: "boxing conditioning bias",
    equipmentReality: "boxing gym and light weights",
    scheduleReality: "4 sessions",
    loggingBehavior: "punchy notes only",
    nutritionBehavior: "good when camp-like, loose otherwise",
    likelyFailureModes: ["domain-specific copy mismatch", "vague goal needs translation"],
    baselineMetrics: { bodyweight: 174, waist: 32 },
  }),
  promptPersona({
    id: "sedentary_tech_worker_hypertension",
    name: "Patrick",
    age: 46,
    trainingAgeYears: 0,
    goalIntents: ["lose weight and become consistent"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "weight loss and consistency over performance",
    strengthContext: "sedentary and deconditioned",
    enduranceContext: "walking only",
    equipmentReality: "home and office gym",
    scheduleReality: "3 short sessions",
    injuryContext: "hypertension risk and low stamina",
    loggingBehavior: "starts honest, then forgets",
    nutritionBehavior: "takeout-heavy",
    likelyFailureModes: ["low capacity", "needs simple safe progression"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 242, waist: 45, startingCapacity: "10_easy_minutes" },
  }),
  promptPersona({
    id: "prediabetic_walking_conditioning",
    name: "Monica",
    age: 52,
    trainingAgeYears: 0,
    goalIntents: ["lose fat safely", "improve my walking fitness"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "safe fat loss",
    strengthContext: "true beginner",
    enduranceContext: "walking-based conditioning",
    equipmentReality: "walking path and light home equipment",
    scheduleReality: "4 walking or light training days",
    injuryContext: "pre-diabetic and cautious",
    loggingBehavior: "steady if the asks stay short",
    nutritionBehavior: "trying to build better routines",
    likelyFailureModes: ["too much friction", "needs walking-first honesty"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 214, waist: 42, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "joint_sensitive_beginner",
    name: "Sandra",
    age: 48,
    trainingAgeYears: 0,
    goalIntents: ["start exercising without hurting my knees"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "general health",
    strengthContext: "beginner with low confidence",
    enduranceContext: "short walks only",
    equipmentReality: "home bike and light weights",
    scheduleReality: "3 short sessions",
    injuryContext: "bad knees and impact sensitivity",
    loggingBehavior: "honest and sparse",
    nutritionBehavior: "average",
    likelyFailureModes: ["impact mismatch", "safe-start baseline needs to be clear"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "20",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 198, startingCapacity: "10_easy_minutes" },
  }),
  promptPersona({
    id: "shoulder_pain_lifter",
    name: "Trevor",
    age: 36,
    trainingAgeYears: 6,
    goalIntents: ["keep making upper-body progress without lighting up my shoulder"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "recomp",
    strengthContext: "experienced lifter who needs substitutions",
    enduranceContext: "minimal conditioning",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions",
    injuryContext: "shoulder pain with heavy pressing",
    loggingBehavior: "excellent",
    nutritionBehavior: "solid",
    likelyFailureModes: ["pain-aware substitutions", "upper-body goal ambiguity"],
    baselineMetrics: { bodyweight: 192, lift: { exercise: "Bench Press", weight: 185, reps: 5 } },
  }),
  promptPersona({
    id: "back_from_injury_reentry",
    name: "Luis",
    age: 27,
    trainingAgeYears: 4,
    goalIntents: ["build confidence and get back in shape"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "general fitness rebuild",
    strengthContext: "used to train consistently, now tentative",
    enduranceContext: "low base after time off",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions",
    injuryContext: "coming back from injury and afraid of setbacks",
    loggingBehavior: "careful when confidence is high",
    nutritionBehavior: "average",
    likelyFailureModes: ["fear of progression", "needs trust-building volume"],
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 178, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "burned_out_dieter",
    name: "Kelsey",
    age: 31,
    trainingAgeYears: 2,
    goalIntents: ["lose fat sustainably after repeated failures"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "diet fatigue and trust sensitivity",
    strengthContext: "some lifting confidence",
    enduranceContext: "walks and occasional bike",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions",
    loggingBehavior: "honest but stops when it feels punishing",
    nutritionBehavior: "history of all-or-nothing dieting",
    coachInteractionBehavior: "needs calm, clear direction",
    likelyFailureModes: ["confidence erosion", "overly aggressive recommendations"],
    baselineMetrics: { bodyweight: 186, waist: 35 },
  }),
  promptPersona({
    id: "former_bodybuilder_sustainable_regain",
    name: "Derek",
    age: 43,
    trainingAgeYears: 12,
    goalIntents: ["regain size without obsessive structure"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "less obsessive hypertrophy regain",
    strengthContext: "experienced lifter rebuilding volume tolerance",
    enduranceContext: "little cardio interest",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good if the plan feels adult",
    nutritionBehavior: "solid, but no appetite for prep-bodybuilder rigidity",
    likelyFailureModes: ["copy feels too amateur", "hypertrophy volume overshoot"],
    baselineMetrics: { bodyweight: 214, waist: 38, lift: { exercise: "Bench Press", weight: 225, reps: 5 } },
  }),
  promptPersona({
    id: "actor_model_appearance_user",
    name: "Chase",
    age: 27,
    trainingAgeYears: 3,
    goalIntents: ["look sharper and more camera-ready by September"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "very appearance-centric outcome with precise look language",
    strengthContext: "basic gym comfort",
    enduranceContext: "mixed conditioning tolerance",
    equipmentReality: "commercial gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good until expectations outrun reality",
    nutritionBehavior: "detail-seeking but inconsistent",
    likelyFailureModes: ["look-language mismatch", "precision expectation gap"],
    baselineMetrics: { bodyweight: 168, waist: 31 },
  }),
  promptPersona({
    id: "dad_35_min_sessions",
    name: "Ben",
    age: 38,
    trainingAgeYears: 5,
    goalIntents: ["stay strong", "not get fat"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "maintenance to mild recomp",
    strengthContext: "experienced but time-constrained",
    enduranceContext: "walks and occasional bike",
    equipmentReality: "garage gym",
    scheduleReality: "3 sessions of about 35 minutes",
    loggingBehavior: "consistent if the flow is quick",
    nutritionBehavior: "family-meal reality",
    likelyFailureModes: ["session-length mismatch", "time pressure"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 201, lift: { exercise: "Back Squat", weight: 255, reps: 5 } },
  }),
  promptPersona({
    id: "mom_3_kids_sane_meals",
    name: "Rachel",
    age: 41,
    trainingAgeYears: 3,
    goalIntents: ["get stronger", "lose fat without meal chaos"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "fat loss with sane meals",
    strengthContext: "moderate home-training experience",
    enduranceContext: "walks and active parenting",
    equipmentReality: "home dumbbells and treadmill",
    scheduleReality: "3 fragmented sessions around family life",
    loggingBehavior: "short and honest",
    nutritionBehavior: "family-driven and imperfect",
    likelyFailureModes: ["too much decision load", "meal support feels fake"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 177, waist: 34 },
  }),
  promptPersona({
    id: "autistic_routine_driven_user",
    name: "Milo",
    age: 25,
    trainingAgeYears: 2,
    goalIntents: ["build strength with a stable routine"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "consistency over aesthetics",
    strengthContext: "enjoys structured progression",
    enduranceContext: "light cardio tolerance",
    equipmentReality: "commercial gym",
    scheduleReality: "4 highly regular sessions",
    loggingBehavior: "excellent when the workflow is deterministic",
    nutritionBehavior: "consistent",
    coachInteractionBehavior: "never chats unless wording gets fuzzy",
    likelyFailureModes: ["ambiguous copy intolerance", "plan churn erodes trust"],
    baselineMetrics: { bodyweight: 165, lift: { exercise: "Bench Press", weight: 135, reps: 5 } },
  }),
  promptPersona({
    id: "adhd_low_friction_user",
    name: "Jules",
    age: 29,
    trainingAgeYears: 1,
    goalIntents: ["get fitter without forgetting the plan"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general fitness and confidence",
    strengthContext: "true beginner",
    enduranceContext: "walks and occasional classes",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions with lots of dropped balls",
    loggingBehavior: "forgets unless the log is nearly prefilled",
    nutritionBehavior: "mixed",
    coachInteractionBehavior: "uses coach only when totally lost",
    likelyFailureModes: ["friction kills consistency", "forgets the next step"],
    baselineMetrics: { bodyweight: 158, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "anxious_beginner_low_text",
    name: "Hannah",
    age: 22,
    trainingAgeYears: 0,
    goalIntents: ["get in shape without feeling overwhelmed"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "confidence-building general fitness",
    strengthContext: "beginner",
    enduranceContext: "minimal",
    equipmentReality: "apartment gym",
    scheduleReality: "3 short sessions",
    loggingBehavior: "good if asked very little",
    nutritionBehavior: "average",
    coachInteractionBehavior: "asks for reassurance often",
    likelyFailureModes: ["too much text", "choice overload"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "20",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 149, startingCapacity: "10_easy_minutes" },
  }),
  promptPersona({
    id: "type_a_optimizer_hal_higdon",
    name: "Neil",
    age: 34,
    trainingAgeYears: 6,
    goalIntents: ["run a marathon with the Hal Higdon plan"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "performance-first",
    strengthContext: "does enough strength to support running",
    enduranceContext: "serious runner and metric optimizer",
    equipmentReality: "road running and commercial gym",
    scheduleReality: "5 training days",
    loggingBehavior: "excellent and detail-heavy",
    nutritionBehavior: "metrics-first",
    coachInteractionBehavior: "overuses coach to compare every option",
    likelyFailureModes: ["external-plan fidelity expectation", "hates fuzzy wording"],
    baselineMetrics: { bodyweight: 172, run: { distanceMiles: 16, paceText: "7:40 pace" } },
  }),
  promptPersona({
    id: "lifter_hates_cardio",
    name: "Spencer",
    age: 26,
    trainingAgeYears: 4,
    goalIntents: ["get stronger and look better without too much cardio"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "aesthetics and strength with cardio resistance",
    strengthContext: "intermediate lifter",
    enduranceContext: "minimal interest",
    equipmentReality: "full gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good in the gym",
    nutritionBehavior: "solid",
    likelyFailureModes: ["conditioning resentment", "hybrid volume pushback"],
    baselineMetrics: { bodyweight: 183, waist: 33, lift: { exercise: "Bench Press", weight: 185, reps: 5 } },
  }),
  promptPersona({
    id: "runner_hates_lifting",
    name: "Maya_R",
    age: 31,
    trainingAgeYears: 5,
    goalIntents: ["run faster without turning my week into a lifting plan"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "performance-first",
    strengthContext: "reluctant strength trainee",
    enduranceContext: "committed runner",
    equipmentReality: "roads and light gym access",
    scheduleReality: "4 runs and 1 optional strength session",
    loggingBehavior: "excellent on runs, poor on strength extras",
    nutritionBehavior: "steady",
    likelyFailureModes: ["strength resistance", "short-session preference"],
    baselineMetrics: { bodyweight: 136, run: { distanceMiles: 8, paceText: "8:05 pace" } },
  }),
  promptPersona({
    id: "construction_worker_recovery_limited",
    name: "Ivan",
    age: 39,
    trainingAgeYears: 2,
    goalIntents: ["get fitter without crushing recovery from work"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "general fitness and modest fat loss",
    strengthContext: "physically active job but limited structured lifting",
    enduranceContext: "job already tiring",
    equipmentReality: "basic gym",
    scheduleReality: "3 tired evening sessions",
    injuryContext: "low-back and shoulder fatigue from work",
    loggingBehavior: "simple and sporadic",
    nutritionBehavior: "convenience-heavy",
    likelyFailureModes: ["recovery overload", "work-capacity mismatch"],
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 224, waist: 41, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "vegetarian_beginner_mass_gain",
    name: "Anika",
    age: 27,
    trainingAgeYears: 0,
    goalIntents: ["gain muscle", "feel more confident"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "lean gain and confidence",
    strengthContext: "beginner lifter",
    enduranceContext: "minimal",
    equipmentReality: "commercial gym",
    scheduleReality: "4 sessions",
    loggingBehavior: "good if simple",
    nutritionBehavior: "worries about protein and under-eats when busy",
    likelyFailureModes: ["protein uncertainty", "benchmark over-asking"],
    baselineMetrics: { bodyweight: 124, waist: 26 },
  }),
  promptPersona({
    id: "frequent_restaurant_eater",
    name: "Tasha",
    age: 32,
    trainingAgeYears: 2,
    goalIntents: ["lose fat without pretending I cook every meal"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "fat loss with real-world food context",
    strengthContext: "some gym confidence",
    enduranceContext: "light conditioning",
    equipmentReality: "commercial gym",
    scheduleReality: "3 sessions",
    loggingBehavior: "fair",
    nutritionBehavior: "frequent restaurants and work dinners",
    coachInteractionBehavior: "wants short, practical food guidance",
    likelyFailureModes: ["nutrition realism mismatch", "restaurant drift"],
    baselineMetrics: { bodyweight: 189, waist: 36 },
  }),
  promptPersona({
    id: "teen_athlete_safe_strength",
    name: "Jason",
    age: 17,
    trainingAgeYears: 1,
    goalIntents: ["get stronger for sports safely"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "performance and confidence",
    strengthContext: "beginner sport athlete",
    enduranceContext: "team practice handles conditioning",
    equipmentReality: "school weight room",
    scheduleReality: "3 lifting sessions around practice",
    loggingBehavior: "good if it feels like sports performance",
    nutritionBehavior: "depends on school and parents",
    likelyFailureModes: ["safety tone matters", "copy must stay clear"],
    baselineMetrics: { bodyweight: 162, lift: { exercise: "Back Squat", weight: 155, reps: 5 } },
  }),
  promptPersona({
    id: "college_swimmer_burnout_return",
    name: "Emma",
    age: 21,
    trainingAgeYears: 7,
    goalIntents: ["love swim training again", "get generally fit"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "confidence and enjoyment over aggression",
    strengthContext: "basic dryland background",
    enduranceContext: "former competitive swimmer returning from burnout",
    equipmentReality: "college pool and rec center",
    scheduleReality: "3 to 4 sessions",
    loggingBehavior: "good if it stays emotionally low-pressure",
    nutritionBehavior: "average",
    likelyFailureModes: ["metric pressure", "burnout if the product sounds severe"],
    baselineMetrics: {
      bodyweight: 149,
      swim: { distance: 1000, distanceUnit: "yd", duration: "18:40", raw: "1000 yd in 18:40" },
      swimAccessReality: "pool",
    },
  }),
  promptPersona({
    id: "open_ended_longevity_user",
    name: "Harold",
    age: 58,
    trainingAgeYears: 2,
    goalIntents: ["stay capable for life"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "open-ended healthspan and capability",
    strengthContext: "moderate machine and dumbbell comfort",
    enduranceContext: "walks regularly",
    equipmentReality: "community gym",
    scheduleReality: "4 short sessions",
    loggingBehavior: "steady",
    nutritionBehavior: "fairly consistent",
    coachInteractionBehavior: "never chats unless something feels off",
    likelyFailureModes: ["deadline language feels wrong", "future horizon confusion"],
    sessionLength: "30",
    preferredIntensity: "Conservative",
    baselineMetrics: { bodyweight: 181, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "wheelchair_upper_body_conditioning",
    name: "Devon",
    age: 35,
    trainingAgeYears: 3,
    goalIntents: ["build upper-body conditioning from my wheelchair"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "conditioning and resilience",
    strengthContext: "upper-body and adaptive training only",
    enduranceContext: "wheelchair-based conditioning",
    equipmentReality: "wheelchair, cables, and bands",
    scheduleReality: "4 sessions",
    injuryContext: "adaptive constraints need to be respected",
    loggingBehavior: "good if the product feels respectful",
    nutritionBehavior: "average",
    likelyFailureModes: ["adaptive domain mismatch", "respect and clarity matter"],
    environmentMode: "Home",
    equipmentAccess: "mixed",
    sessionLength: "30",
    baselineMetrics: { startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "language_imprecise_guidance_user",
    name: "Rick",
    age: 40,
    trainingAgeYears: 1,
    goalIntents: ["uh just not feel gross and get kinda stronger and slimmer I guess"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "messy vague text with mixed appearance and strength intent",
    strengthContext: "low confidence",
    enduranceContext: "some walking",
    equipmentReality: "basic gym",
    scheduleReality: "3 sessions",
    loggingBehavior: "simple and uneven",
    nutritionBehavior: "mixed",
    coachInteractionBehavior: "asks for clarification when confused",
    likelyFailureModes: ["messy goal text", "needs efficient guidance"],
    baselineMetrics: { bodyweight: 197, waist: 38, startingCapacity: "20_to_30_minutes" },
  }),
  promptPersona({
    id: "pro_baseball_cut_then_delete",
    name: "Rafael",
    age: 24,
    trainingAgeYears: 8,
    goalIntents: ["lose 10 pounds but retain muscle"],
    supportTierExpectation: "tier_3",
    bodyCompContext: "performance-preserving cut for a pro athlete",
    strengthContext: "advanced strength base",
    enduranceContext: "sport practice handles conditioning",
    equipmentReality: "pro facility",
    scheduleReality: "5 sessions until he deletes the account after 12 weeks",
    loggingBehavior: "high detail until he disengages",
    nutritionBehavior: "team-support environment",
    coachInteractionBehavior: "rarely chats with coach",
    likelyFailureModes: ["pro-sport specificity", "account deletion after 3 months"],
    baselineMetrics: { bodyweight: 212, waist: 36, lift: { exercise: "Bench Press", weight: 245, reps: 3 } },
  }),
  promptPersona({
    id: "powerlifter_bench_aesthetics_exact",
    name: "Shawn",
    age: 31,
    trainingAgeYears: 5,
    goalIntents: ["bench 225", "look bigger through my chest and shoulders"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "upper-body aesthetics secondary goal",
    strengthContext: "four-day powerbuilding split",
    enduranceContext: "minimal conditioning",
    equipmentReality: "full gym",
    scheduleReality: "4 lifting days available",
    loggingBehavior: "excellent on primary work",
    nutritionBehavior: "solid calories, inconsistent meal timing",
    likelyFailureModes: ["secondary-goal hiding", "milestone realism"],
    baselineMetrics: { bodyweight: 186, lift: { exercise: "Bench Press", weight: 195, reps: 4 } },
  }),
  promptPersona({
    id: "night_shift_nurse_energy_bodycomp",
    name: "Tori",
    age: 34,
    trainingAgeYears: 2,
    goalIntents: ["improve body composition", "have more energy on night shift"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "body composition with sleep disruption",
    strengthContext: "basic lifting comfort",
    enduranceContext: "walks a lot at work",
    equipmentReality: "hospital gym and home dumbbells",
    scheduleReality: "2 to 4 sessions around rotating night shifts",
    loggingBehavior: "sporadic but truthful",
    nutritionBehavior: "inconsistent meal timing and snack drift",
    coachInteractionBehavior: "asks for help when sleep is wrecked",
    likelyFailureModes: ["sleep disruption", "nutrition drift"],
    environmentMode: "Home",
    equipmentAccess: "dumbbells",
    sessionLength: "30",
    baselineMetrics: { bodyweight: 174, waist: 34 },
  }),
  promptPersona({
    id: "obstacle_course_mixed_goal_user",
    name: "Blake",
    age: 32,
    trainingAgeYears: 3,
    goalIntents: ["get ready for an obstacle-course race", "improve grip and conditioning"],
    supportTierExpectation: "tier_2",
    bodyCompContext: "mixed performance goal",
    strengthContext: "moderate lifting base",
    enduranceContext: "weekend race conditioning",
    equipmentReality: "commercial gym and outdoor trails",
    scheduleReality: "4 sessions",
    loggingBehavior: "good",
    nutritionBehavior: "steady",
    likelyFailureModes: ["mixed-domain translation", "grip goal can get hidden"],
    baselineMetrics: { bodyweight: 187, lift: { exercise: "Deadlift", weight: 275, reps: 5 } },
  }),
  promptPersona({
    id: "hostile_trainer_anti_ai",
    name: "Grant",
    age: 44,
    trainingAgeYears: 18,
    goalIntents: ["keep my strength high", "keep my conditioning sharp without generic filler"],
    supportTierExpectation: "tier_1",
    bodyCompContext: "skeptical veteran trainer using the product to hunt for contradictions and embarrass it in front of clients",
    strengthContext: "experienced coach and lifter with strong opinions about exercise selection and progression logic",
    enduranceContext: "wants useful conditioning support but hates canned running theater and dumb generic circuits",
    equipmentReality: "full gym, turf, and enough equipment to notice lazy programming",
    scheduleReality: "4 sessions between client blocks while actively pressure-testing the app",
    loggingBehavior: "logs enough detail to pressure-test adaptations and look for contradictions",
    nutritionBehavior: "solid habits; mostly evaluating training logic, not meal advice",
    coachInteractionBehavior: "hostile and argumentative, using coach replies to challenge whether the app is trying to replace trainers",
    likelyFailureModes: [
      "generic prescriptive workouts trigger ridicule",
      "trainer-replacement tone destroys trust immediately",
      "any contradiction across surfaces becomes a screenshot for clients",
      "support work must look deliberate instead of padded filler",
    ],
    baselineMetrics: {
      bodyweight: 208,
      waist: 37,
      lift: { exercise: "Bench Press", weight: 235, reps: 5 },
      run: { distanceMiles: 3, paceText: "8:20 pace" },
    },
  }),
];

const SUPPORT_TIER_EXPECTATION_OVERRIDES = {
  novice_obese_beginner: "tier_2",
  detrained_returner: "tier_2",
  no_goal_foundation_user: "tier_3",
  injury_prone_runner: "tier_1",
  hybrid_athlete_split: "tier_1",
  triathlon_sprinter: "tier_2",
  dancer_power_endurance: "tier_1",
  senior_rehab_walk: "tier_1",
  crossfit_burnout_returner: "tier_2",
  firefighter_candidate: "tier_2",
  police_shift_worker: "tier_2",
  military_prep_candidate: "tier_1",
  pickleball_retiree: "tier_1",
  climber_body_comp: "tier_1",
  peloton_plus_strength_user: "tier_2",
  minimalist_foundation_user: "tier_2",
  ocr_weekend_warrior: "tier_1",
  college_rower_offseason: "tier_1",
  older_return_to_health: "tier_2",
  desk_worker_foundation: "tier_2",
  masters_lifter_over50: "tier_2",
  celebrity_look_request: "tier_1",
  hyrox_style_user: "tier_2",
  minimal_equipment_conditioning_user: "tier_2",
  older_adult_capable_mobility: "tier_2",
  pickup_basketball_dad: "tier_1",
  boxing_fighter_shape: "tier_1",
  jiu_jitsu_cut_performance: "tier_1",
  shoulder_pain_lifter: "tier_1",
  actor_model_appearance_user: "tier_1",
  dad_35_min_sessions: "tier_2",
  adhd_low_friction_user: "tier_2",
  anxious_beginner_low_text: "tier_2",
  type_a_optimizer_hal_higdon: "tier_1",
  open_ended_longevity_user: "tier_2",
  wheelchair_upper_body_conditioning: "tier_2",
  pro_baseball_cut_then_delete: "tier_1",
  obstacle_course_mixed_goal_user: "tier_1",
};

export const SYNTHETIC_ATHLETE_PERSONAS = Object.freeze([
  ...BASE_SYNTHETIC_ATHLETE_PERSONAS,
  ...ADDITIONAL_ADVERSARIAL_PERSONAS,
].map((persona) => ({
  ...persona,
  supportTierExpectation: SUPPORT_TIER_EXPECTATION_OVERRIDES[persona.id] || persona.supportTierExpectation,
})));

export const SYNTHETIC_ATHLETE_PERSONA_COUNT = SYNTHETIC_ATHLETE_PERSONAS.length;
