export {
  runSyntheticAthleteLab,
  SYNTHETIC_ATHLETE_CATALOG_MODES,
  SYNTHETIC_ATHLETE_RELEASE_GATE_PERSONA_IDS,
  SYNTHETIC_ATHLETE_RELEASE_GATE_SCHEMA_VERSION,
  SYNTHETIC_ATHLETE_RELEASE_GATE_THRESHOLD_PROPOSAL,
} from "./adversarial-harness.js";
